name: 'setup-chromedriver'
description: 'Setup chromedriver'
author: 'nanasess'
inputs:
  chromedriver-version:
    description: 'The chromedriver version to install'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'

